dotnet build TransactionsManagement\Transactions\Transactions.csproj
dotnet test TransactionsManagement\TransactionsTests\TransactionsTests.csproj
start dotnet run --project TransactionsManagement\Transactions\Transactions.csproj
